local transaction = require("truth-table.transaction")
local predicate = require("truth-table.predicate")
local rewrite = require("truth-table.rewrite")
local trees = require("truth-table.trees")

describe("transactions", function()
    local function increment(value)
        return transaction.record(value + 1, { before = value, after = value + 1, law = "increment" })
    end

    it("satisfies left identity, right identity and associativity", function()
        assert.are.same(increment(2), transaction.bind(transaction.pure(2), nil, increment))
        local tx = increment(2)
        assert.are.same(tx, transaction.bind(tx, nil, transaction.pure))
        local left = transaction.bind(transaction.bind(tx, nil, increment), nil, increment)
        local right = transaction.bind(tx, nil, function(value)
            return transaction.bind(increment(value), nil, increment)
        end)
        assert.are.same(left, right)
        assert.are.equal(3, #left.changes)
        assert.are.equal(1, #tx.changes)
    end)

    it("short-circuits a refusal without publishing a partial log", function()
        local called = false
        local value, err = transaction.bind(nil, "refused", function()
            called = true
        end)
        assert.is_nil(value)
        assert.are.equal("refused", err)
        assert.is_false(called)
        value, err = transaction.bind(increment(2), nil, function() return nil, "later refusal" end)
        assert.is_nil(value)
        assert.are.equal("later refusal", err)
    end)

    it("keeps a law's trees and its consumed and produced terms in its record", function()
        local before = assert(predicate.parse_located("r ∧ ¬(s ∨ t)"))
        local tx = assert(rewrite.de_morgan(before, 7))
        local change = tx.changes[1]
        assert.are.equal(before, change.before)
        assert.are.equal(tx.value, change.after)
        local text, regions = trees.rendered(tx.value, change.produced)
        assert.are.equal("¬s ∧ ¬t", text:sub(regions[1][1] + 1, regions[1][2]))
        assert.are.same(change.produced_ranges, regions)
        assert.are.equal("¬(s ∨ t)", ("r ∧ ¬(s ∨ t)"):sub(change.consumed_ranges[1][1] + 1, change.consumed_ranges[1][2]))
        assert.is_nil(before.changed)
        assert.is_nil(tx.value.changed)
    end)

    it("composes cursor rewrites without reparsing or annotating output trees", function()
        local before = assert(predicate.parse_located("¬(A ∨ B)"))
        local first = assert(rewrite.de_morgan(before))
        local combined = assert(transaction.bind(first, nil, function(tree)
            return rewrite.commute(tree, 1)
        end))
        assert.are.equal("¬B ∧ ¬A", trees.heading(combined.value))
        assert.are.equal(2, #combined.changes)
        assert.are.equal(first.value, combined.changes[2].before)
        assert.are.same({ { 0, #"¬A" }, { #"¬A ∧ ", #"¬A ∧ ¬B" } }, combined.changes[2].consumed_ranges)
        -- The first change's consumed ranges are in the source's text, the
        -- last change's produced ranges in the result's: what a preview of
        -- the composed rewrite lights at each end.
        assert.are.same({ { 0, #"¬(A ∨ B)" } }, combined.changes[1].consumed_ranges)
        assert.are.same({ { 0, #"¬B ∧ ¬A" } }, combined.changes[2].produced_ranges)
        assert.is_nil(first.value.span)
        assert.is_nil(first.value.changed)
        local collapsed = assert(transaction.bind(assert(rewrite.commute(
            assert(predicate.parse_located("A ∧ 1")), 1)), nil, function(tree)
            return rewrite.simplify(tree, 1)
        end))
        assert.are.equal("A", trees.heading(collapsed.value))
    end)
end)
